- src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- src/main/java/io/sugo/android/mpmetrics/MPDbAdapter.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- src/main/java/io/sugo/android/viewcrawler/DynamicEventTracker.java
修改数据上报格式
将客户端时间维度time时间戳修改为Date
修改h5事件绑定方法
页面时长修改为两位小数
> Fix #52 修改数据上报格式

- src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
> fix xwalk #45

- src/main/java/io/sugo/android/viewcrawler/ViewSnapshot.java
> fix #76 #77

- src/main/java/io/sugo/android/mpmetrics/SugoPageManager.java
> 提升查询页面名称的性能

- src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- src/main/java/io/sugo/android/mpmetrics/SystemInformation.java
> fix js v2.2 and add deviceId

- README.md
> Fix sdk doc

- src/main/java/io/sugo/android/viewcrawler/ViewCrawler.java
> fix onFlipGesture

- src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebEventListener.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- src/main/java/io/sugo/android/viewcrawler/ViewCrawler.java
> fix dynamic inject webview js

- src/main/java/io/sugo/android/mpmetrics/SugoWebEventListener.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
fix dynamic inject js in xwalkview
> fix dynamic inject js in xwalkview

- src/main/java/io/sugo/android/mpmetrics/SystemInformation.java
> fix device id

- src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoActivityLifecycleCallbacks.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
> fix event name

- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
> fix event type

- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
> fix js v2.9 and add \n

- README.md
- library/src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- library/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library/src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- library/src/main/java/io/sugo/android/util/HttpService.java
- sugoandroidsdk-xwalkview-demo/src/main/AndroidManifest.xml
- sugoandroidsdk-xwalkview-demo/src/main/java/me/owj/android_xwalkview_demo/MainActivity.java
fix dimens and new startSugo API
> fix dimens and new startSugo API

- README.md
- src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoPageManager.java
- src/main/java/io/sugo/android/util/HttpService.java
fix startSugo and full dimensions in debug
> fix startSugo and full dimensions in debug

- library/src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- sugoandroidsdk-xwalkview-demo/src/main/java/me/owj/android_xwalkview_demo/WebActivity.java
> fix h5 path with hash

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- library/build.gradle
- library/src/main/java/io/sugo/android/mpmetrics/MPDbAdapter.java
- library/src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- library/src/main/java/io/sugo/android/mpmetrics/SugoActivityLifecycleCallbacks.java
- library/src/main/java/io/sugo/android/mpmetrics/SugoDimensionManager.java
- library/src/main/java/io/sugo/android/mpmetrics/SugoPageManager.java
- library/src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- sugoandroidsdk-xwalkview-demo/build.gradle
- sugoandroidsdk-xwalkview-demo/src/main/AndroidManifest.xml
- sugoandroidsdk-xwalkview-demo/src/main/assets/index.html
- sugoandroidsdk-xwalkview-demo/src/main/java/me/owj/android_xwalkview_demo/MainActivity.java
- sugoandroidsdk-xwalkview-demo/src/main/java/me/owj/android_xwalkview_demo/NativePageActivity.java
- sugoandroidsdk-xwalkview-demo/src/main/java/me/owj/android_xwalkview_demo/WebActivity.java
- sugoandroidsdk-xwalkview-demo/src/main/java/me/owj/android_xwalkview_demo/fragments/MyFragment.java
- sugoandroidsdk-xwalkview-demo/src/main/res/layout/activity_native_page.xml
- sugoandroidsdk-xwalkview-demo/src/main/res/layout/fragment_my.xml
- sugoandroidsdk-xwalkview-demo/src/main/res/values/strings.xml
- sugoandroidsdk-xwalkview-demo/src/main/res/values/styles.xml
1 Fragment 追踪代码埋点
2 调整非期望类型的维度数据类型
3 默认的 dimensions data type
4 移除后台停留，窗口退出，页面退出事件
5 移除 /data/data /data/user/0 路径名称
> many feature update

- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
除去 url 中可能存在的 /data/data 之类的前缀。
> remove /data/data

- src/main/java/io/sugo/android/mpmetrics/SugoActivityLifecycleCallbacks.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebEventListener.java
1 修改 启动、后台、唤醒、退出、APP停留的页面名称
2 修复 WEB 页面的 停留 事件
3 修复 退出事件和 APP 停留事件
> Fix web 停留事件

- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
1 没有页面名称的事件，页面名称都改成事件名称
2 APP安装事件，写死应用名称【无限极中国APP】
3 增加 javascript
> app 安装 - js - 页面名称

- src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
> app 安装页面名称

- src/main/java/io/sugo/android/mpmetrics/SugoWebEventListener.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
2 fix ConcurrentModificationException
> 1 fix touchend event

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/sugo/sdkdemo/activity/MainActivity.java
- library/src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- library/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library/src/main/java/io/sugo/android/viewcrawler/ViewVisitor.java
> Fix update decide interval

- src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
修改 beforeunload 为 unload
development 模式时，不请求 decide
> 修改 track js 为字符串替换法来进行注入前的处理

- gradle.properties
- settings.gradle
- src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- src/main/java/io/sugo/android/mpmetrics/SugoActivityLifecycleCallbacks.java
- src/main/java/io/sugo/android/mpmetrics/SugoPageManager.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebNodeReporter.java
- src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- src/main/java/io/sugo/android/viewcrawler/UpdatesFromMixpanel.java
- src/main/java/io/sugo/android/viewcrawler/ViewCrawler.java
- src/main/java/io/sugo/android/viewcrawler/ViewSnapshot.java
自动上报web的 document.title …
全局元素
页面分类
es6 降为 es5
> Crosspage pagecategory xwalk

- library-wxj/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/DynamicEventTracker.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/EditProtocol.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/ViewCrawler.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/ViewSnapshot.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/ViewVisitor.java
> Wxj submit earn attr

- library-wxj/src/main/assets/Sugo.js
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
fix apkversion and delete js file with sugoio
> fix sdkVesion and delete sugoio

- library-wxj/build.gradle
- library-wxj/src/main/java/io/sugo/android/mpmetrics/DecideChecker.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/InitSugoCallback.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/ViewCrawler.java
- library_heatmap/build.gradle
- library_heatmap/src/main/java/io/sugo/heatmap/SugoHeatMapCallbacks.java
- library_heatmap/src/main/java/io/sugo/heatmap/SugoHeatMapManager.java
添加一个接口，接收是否初始化sdk，上传屏幕位置，上传坐标字段，同时上传坐标时间间隔以新接口为准
> Wxj add sugo init api

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/sugo/sdkdemo/App.java
- library-wxj/build.gradle
- library-wxj/src/main/java/io/sugo/android/mpmetrics/AnalyticsMessages.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/BackgroundCapture.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/ConfigurationChecker.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/DecideChecker.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/DecideMessages.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/MPDbAdapter.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/ResourceReader.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoActivityLifecycleCallbacks.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoDimensionManager.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoWebEventListener.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SystemInformation.java
- library-wxj/src/main/java/io/sugo/android/util/ExceptionInfoUtils.java
- library-wxj/src/main/java/io/sugo/android/util/HttpService.java
- library-wxj/src/main/java/io/sugo/android/util/ImageStore.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/DynamicEventTracker.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/SugoHeatMap.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/ViewCrawler.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/ViewSnapshot.java
- library-wxj/src/main/java/io/sugo/android/viewcrawler/ViewVisitor.java
增加三个字段，分别是事件版本号，纬度版本号，还有是否强制拉取配置
> add three params to sugo init api

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/sugo/sdkdemo/activity/WebActivity.java
- app/src/main/java/io/sugo/sdkdemo/activity/WebViewMoreActivity.java
- app/src/main/res/layout/more_webview.xml
- library-wxj/build.gradle
- library-wxj/src/main/assets/Sugo.js
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoActivityLifecycleCallbacks.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoWebEventListener.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoWebViewClient.java
- library_heatmap/build.gradle
- library_heatmap/src/main/java/io/sugo/heatmap/SugoHeatMapCallbacks.java
- settings.gradle
当在一个activity中启动多个webview时，某个webview退出时，会自动记录当前webview的页面路径，以供屏幕点击事情上报路径使用
> Wxj more webview

- library-wxj/build.gradle
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library_heatmap/build.gradle
> fix sdk  version

- library-wxj/build.gradle
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SGConfig.java
- library-wxj/src/main/java/io/sugo/android/mpmetrics/SugoAPI.java
> fix page_name decide
